on:
  create:
    branches:
      - '*'

jobs:
  move-issue-to-in-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move Issue to In Progress
        run: |
          # Get the issue number from the branch name (assuming it's a numeric part of the branch name)
          ISSUE_NUMBER=$(echo "$GITHUB_REF" | sed 's/[^0-9]*//g')

          if [[ -n "$ISSUE_NUMBER" ]]; then
            # Find the project column ID for "In Progress" (replace with your column's name)
            COLUMN_ID=$(curl -s "https://api.github.com/projects/columns" -H "Authorization: Bearer $GHPROJECT_TOKEN" | jq -r '.[] | select(.name == "In Progress") | .id')

            if [[ -n "$COLUMN_ID" ]]; then
              # Create a card in the "In Progress" column for the issue
              CARD_ID=$(curl -X POST "https://api.github.com/projects/columns/$COLUMN_ID/cards" -H "Authorization: Bearer $GHPROJECT_TOKEN" -d '{"content_id": '"$ISSUE_NUMBER"',"content_type": "Issue"}' | jq -r '.id')

              if [[ -n "$CARD_ID" ]]; then
                # Move the card to the top of the column
                curl -X POST "https://api.github.com/projects/columns/cards/$CARD_ID/moves" -H "Authorization: Bearer $GHPROJECT_TOKEN" -d '{"position": "top"}'
              fi
            fi
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}
