name: Test Pull Request Before Merge With Dev

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  Test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
