name: Test Pull Request Before Merge With Dev

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  Test-Pull-Request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm ci  test
        run: |
          npm ci
          npm test
